name: mpn_info_flutter
description: "MPN-Info Flutter - A modern tax revenue processing application for Indonesian tax offices"
publish_to: 'none' # This is a private application

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4  # For desktop support
  path: ^1.8.3
  path_provider: ^2.1.4
  mysql1: ^0.20.0  # MySQL support
  
  # HTTP & Networking
  dio: ^5.3.4
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  
  # Charts & Data Visualization
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: 31.1.22
  
  # File Operations
  file_picker: ^6.1.1
  excel: ^4.0.2
  pdf: ^3.10.7
  csv: ^6.0.0
  
  # UI Components & Tables
  data_table_2: ^2.5.11
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  uuid: ^4.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  intl: ^0.20.2
  
  # Desktop Integration
  window_manager: ^0.3.7
  
  # Logging
  logger: ^2.0.2+1
  
  # Navigation
  go_router: ^12.1.3
  
  # Responsive Design
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Custom fonts will be added later
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
